### ISSUE TITLE
textmodel_newsmap can't deal with list columns

### ISSUE THREAD

**Issue by JBGruber** [koheiw/newsmap#23]
If there is a list column in the corpus, `textmodel_newsmap` will produce hundreds of `NAs introduced by coercion` warnings.

# Reprex

I'm using the demo code here with two changed lines to change a column into a list and to subset the data:

```
download.file('https://www.dropbox.com/s/e19kslwhuu9yc2z/yahoo-news.RDS?dl=1', '~/yahoo-news.RDS')
library(newsmap)
library(quanteda)

# Load data
data <- readRDS('~/yahoo-news.RDS')


data$text <- paste0(data$head, ". ", data$body)
data$body <- NULL

# make list and draw small subset
data <- data[1:200, ]
data$head <- as.list(data$head)

corp <- corpus(data, text_field = 'text')

# Custom stopwords
month <- c('January', 'February', 'March', 'April', 'May', 'June',
           'July', 'August', 'September', 'October', 'November', 'December')
day <- c('Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday')
agency <- c('AP', 'AFP', 'Reuters')

# Select training period
#sub_corp <- corpus_subset(corp, '2014-01-01' <= date & date <= '2014-12-31')

# Tokenize
toks <- tokens(corp)
toks <- tokens_remove(toks, stopwords('english'), valuetype = 'fixed', padding = TRUE)
toks <- tokens_remove(toks, c(month, day, agency), valuetype = 'fixed', padding = TRUE)

label_toks <- tokens_lookup(toks, data_dictionary_newsmap_en, levels = 3) # level 3 is countries
label_dfm <- dfm(label_toks)

feat_dfm <- dfm(toks, tolower = FALSE)
feat_dfm <- dfm_select(feat_dfm, selection = "keep", '^[A-Z][A-Za-z1-2]+', valuetype = 'regex', case_insensitive = FALSE) # include only proper nouns to model
feat_dfm <- dfm_trim(feat_dfm, min_termfreq = 10)

model <- textmodel_newsmap(feat_dfm, label_dfm)
```
This will produces hundreds of warnings that were hard for me to make sense of at first. They look like this:

```
> warnings()
Warning messages:
1: In qatd_cpp_is_grouped_numeric(as.numeric(x), group) :
  NAs introduced by coercion
2: In qatd_cpp_is_grouped_numeric(as.numeric(x), group) :
  NAs introduced by coercion
...
```
# Intended behaviour

Not sure how often this comes up and in my case it was actually a good thing since I created the list column by accident. But it might not be the best behaviour with the cryptic error and all. Either the error should be meaningful if this causes problems with the model or there shouldn't be warnings, I think.

***Note: Otherwise this is a fantastic package! I tried to classify news by using the Geonames dataset as dictionary and newsmap is so much faster and (as it seems) more accurate!***

**Comment by koheiw** [comment]
Thanks @JBGruber the warnings are from `quanteda::dfm_group()` (which I wrote) but it is better to drop document variable in  `textmodel_newsmap()`. It makes estimation faster too!

**Comment by koheiw** [comment]
Please try the master.

**Comment by JBGruber** [comment]
Sorry, I'm not sure what you mean. There hasn't been a commit to master in the meantime. And the issue-23 branch was deleted.

**Comment by koheiw** [comment]
True, I forgot click the merge button! Done.

**Comment by JBGruber** [comment]
Works perfectly now!
