### ISSUE TITLE
Tidy up Italian dictionary

### ISSUE THREAD

**Issue by koheiw** [koheiw/newsmap#32]
@giucarny there is `()` in Austria that looks like an error. How should it correct?
https://github.com/koheiw/newsmap/blob/c6349ab284b23ea9982b27ab2eb98dcd0ec54d19/dict/italian.yml#L249

**Comment by giucarny** [comment]
Sorry for the late reply and the error. The parenthesis should be simply substituted with a *, thus:
` 'AT': [Austria, Vienna, austriac*] `
