### ISSUE TITLE
predict() returns "Error in x[, feature] : Subscript out of bounds"

### ISSUE THREAD

**Issue by SCommain** [koheiw/newsmap#39]
I run into an error with ```predict()``` when trying to predict which topic is most strongly associated with each sentence in my data: R throws the following error:
```
"Error in x[, feature] : Subscript out of bounds"
```
I don't see where the error could come from...
I attach the code I use (for applying the dictionnary first, and then for fitting the newsmap model), together with the dictionary and the tokens object. 
Thanks in advance for your help!
[Files.zip](https://github.com/koheiw/newsmap/files/4667289/Files.zip)

**Comment by koheiw** [comment]
@SCommain , Thanks for sending the file. It is a bug in **quanteda** that we will fix soon. For the moment, you can avoid the problem by `dfm(toksSent, remove = "")`.

Unrelated to the issue, I also noticed that your regex dictionary is too ambiguous. For example "of" in "72_5 of rwas" matches "off", "coffee" etc without "^of$".

**Comment by koheiw** [comment]
Please use the development version of quanteda.
