### ISSUE TITLE
What is the dictionary pattern for Ho Chi Minh City?

### ISSUE THREAD

**Issue by koheiw** [koheiw/newsmap#47]
It is "Ho Chi Minh City" in the English master, but it is without "City" in HE and ES:
https://github.com/koheiw/newsmap/blob/59b025767a21e1f5d110aaa731284b85f4df3eab/dict/hebrew.yml#L176
https://github.com/koheiw/newsmap/blob/59b025767a21e1f5d110aaa731284b85f4df3eab/dict/spanish.yml#L176

Italian has both with and without "City":
https://github.com/koheiw/newsmap/blob/59b025767a21e1f5d110aaa731284b85f4df3eab/dict/italian.yml#L176

"Ho Chi Minh" is the name of the leader in the past. Do people call Ho Chi Minh City without "City" often? This is a similar ambiguity problem between "Washington DC" and "Washington" 😵‍

**Comment by danimadrid** [comment]
This one is tricky. So, the recommended name for the city is, simply "Ho Chi Minh" according to https://www.fundeu.es/recomendacion/ho-chi-minh/ which is the equivalent of the AP Stylebook for Spanish. They also allow two other options: "Ciudad Ho Chin Minh" and "Saigón", but these are less preferred options...

**Comment by koheiw** [comment]
It makes sense to comply with the style guides for journalists. Ho Chi Minh City attracted my attention because @bah-elly is making the Portuguese dictionary: https://github.com/koheiw/newsmap/pull/46

**Comment by danimadrid** [comment]
Now that I've looked into it, it might be worth adding "Saigón" as some news media might still use it, but "Ciudad Ho Chi Minh" isn't really needed, as "Ho Chi Minh" alone would already capture those matches.

**Comment by giucarny** [comment]
Hi there. I guess that for the Italian dictionary can be followed the same approach suggested by Dani for the Spainsh one. Also in Italy it's not impossible to find articles mentioning "Saigon", and I believe that "Città di Ho Chi Minh" can be simply dropped out.

**Comment by koheiw** [comment]
Thank you for your input. Let's add "Saigon" and drop the "City" part then.

**Comment by eladseg** [comment]
In Hebrew it is the same. I saw in the news the use of:

הו צ'י מין - Ho Chi Minh
הו צ'י מין סיטי - Ho Chi Minh City

but I agree that those who wish to include historical reference or working with news archives could also use its former name:

סייגון - Saigón

**Comment by koheiw** [comment]
I don't think we should include historical names, but Saigon seems to be still used by the locals.

When I searched Japan's Google News for Saigon (サイゴン), articles about these appeared. This is a strong case to add Saigon to the English master and update all other languages.

https://en.wikipedia.org/wiki/Saigon_One_Tower
https://en.wikipedia.org/wiki/Saigon_FC

**Comment by koheiw** [comment]
Why don't you guys edit your files? You can edit and issue a PR on the web interface.

**Comment by eladseg** [comment]
done

**Comment by chainsawriot** [comment]
@koheiw I don't want to complicate things, but in Chinese it's almost always with "city" (胡志明"市"). And the Chinese name of Saigon (西貢) is kind of problematic because there is a place with exactly [the same name in Hong Kong](https://en.wikipedia.org/wiki/Sai_Kung_Town).

**Comment by koheiw** [comment]
Thank you for your input. I already knew that it is complex issue :face_with_spiral_eyes:   We can keep "City" of Ho Chi Minh City for Chinese (and probably Japanese) if it is very common. Saigon is interesting. How do people distinguish between 西貢 in Vietnam and Hong Kong? Do they still use 西貢 to refer to Vietnam's city often? I assume only western countries prefer Saigon to Ho Chi Ming City.

**Comment by chainsawriot** [comment]
@koheiw I think in the Chinese context, journalists (especially those in Hong Kong) almost never use 西貢 to refer to the Vietnamese city. The recent revival of interest to the Fall of Saigon (西貢淪陷) in relation to the retreat of the US troop from Afghanistan ([an example](https://www.cna.com.tw/news/firstnews/202108130302.aspx) here) is probably the only reference where 西貢 is used to refer to the Vietnamese city.

**Comment by koheiw** [comment]
In principle, we don't include historical names, so 西貢淪陷 is an exception. Let's keep Chinese dictionaries as they are.

**Comment by koheiw** [comment]
@daiyamao what do you think about adding Saigon to Arabic and Japanese dictionaries?

**Comment by daiyamao** [comment]
I do not disagree.  Shall I add Saigon in Arabic?

**Comment by koheiw** [comment]
Please do add Saigon if it is still commonly used. Do you have "city" in Ho Chi Minh City? If so, do we need it in Arabic?

**Comment by daiyamao** [comment]
I added Saigon. please check if I did correctly. there is city in Ho Chi Minh City.

**Comment by koheiw** [comment]
We decided to change "Ho Chi Minh City" to "Ho Chi Minh" in European languages. Should be make the same change in Arabic? I am still thinking if "ホーチミン” is more common than "ホーチミン市" for the Japanese dictionary.
