### ISSUE TITLE
Make dictionary categories identical across languages

### ISSUE THREAD

**Issue by koheiw** [koheiw/newsmap#8]
Thanks to @danimadrid, this package is becoming extremely useful for international news analysis. To ensure that these dictionaries are comparable, we need to

- [x] Add `CC` for Cock Island to EN, DE, JA
- [x] Sort countries in a meaningful order (alphabetical or latitudinal?)

It is important to keep the order of the countries identical, because resulting DFMs should have columns in the same order. 

@danimadrid I saw you changed the order of the countries. What was the underlying rule?

**Comment by danimadrid** [comment]
I ordered them alphabetically by ISO-2, but I can change it to the same order as the English dic.

**Comment by koheiw** [comment]
@danimadrid , That makes sense, so I will do the same to others later.
